# Site
name: "Zach Peranich"
title: "Mediumish"
description: "Welcome to my first website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
# baseurl: /mediumish-theme-jekyll
# google_analytics: 
#disqus: 'zachperanich'
# mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  syd:
    name: "Sydney Novak"
    display_name: Sydney
    avatar: 'assets/images/SydneyN.jpg'
    email: sydnovak60@gmail.com
    twitter: https://twitter.com/sydnovak60
    description: "Aspiring blogist."
  zach:
    name: "Zach Peranich"
    display_name: Zach
    #avatar: 'assets/images/SydneyN.jpg'
    email: ztperanich@gmail.com
    description: "Zach"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: 
# adsense-data-ad-slot: 

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
